#!/bin/bash
source /var/cld/bin/include/cldfuncs

if grep -q "^ZABBIXCONTROL=" /var/cld/creds/creds
then
    echo -n ""
else
    echo "Will you using Zabbix control module ?" 
    select ANSWER in yes no
    do
        if [ "${ANSWER}" == "yes" ]
            then
                init-load-constants ZABBIX_USER\|zabbix ZABBIX_PASS\|pAs5w0Rd ZABBIX_SERVER\|zbx.example.com ZABBIX_API\|https://zbx.example.com/api_jsonrpc.php ZABBIX_HOSTGROUPID\|10 ZABBIX_TEMPLATEIDS\|10362,10364,10365
                echo ZABBIXCONTROL=1 >> /var/cld/creds/creds
                break
        elif [ "${ANSWER}" == "no" ]
            then
                echo ZABBIXCONTROL=0 >> /var/cld/creds/creds
                break
        fi
    done
fi