#!/bin/bash
#echo $1 | grep -q "^$" || export VMID=$1
cat << EOL | grep -v '^$' | awk '{print "echo $(echo "$1" | md5sum | head -c 8) "$1}' | bash > /var/cld/creds/id_list
$(for GROUP in $(ls /var/cld/access/groups/)
do
grep -qs "1" /var/cld/access/groups/${GROUP}/type \
&& cat /var/cld/access/groups/${GROUP}/clouds 2>/dev/null \
|| sed -r 's#(.*_.*_[0-9]+_[a-zA-Z0-9]+)_.*#\1#g' /var/cld/access/groups/${GROUP}/clouds 2>/dev/null
done)
EOL
