#!/bin/bash
source /var/cld/bin/include/cldfuncs
source /var/cld/creds/creds_backup_monitoring

[ "$SUDO_USER" = "" ] && SUDO_USER=admin
for VM in $(CLOUDS_USER_ALLOWED)
do
timeout 60 cldmount $VM || continue
LOCALMOUNTPATH="/home/${SUDO_USER}/mnt/${VM}"

mkdir -p /backup/files/all_etc/ &>/dev/null

if grep -qi "debian\|ubuntu" /etc/*-release
then
timeout 300 tar --exclude=*.gz --exclude=*.log --exclude=*/selinux/targeted/* -cvzf /backup/files/all_etc/${VM}_etc.tar.gz $LOCALMOUNTPATH/etc
elif grep -qi "centos\|rhel\|fedora" /etc/*-release
then
timeout 300 tar -cvzf /backup/files/all_etc/${VM}_etc.tar.gz $LOCALMOUNTPATH/etc --exclude=*.gz --exclude=*.log --exclude=*/selinux/targeted/*
fi

umount $LOCALMOUNTPATH
fusermount -uz $LOCALMOUNTPATH &>/dev/null
done

mkdir -p ${ETC_BACKUP_PATH}/$(date +%F) &>/dev/null
rsync -avP /backup/files/all_etc/ ${ETC_BACKUP_PATH}/$(date +%F)/
