#!/bin/bash
source /var/cld/bin/include/cldfuncs

init-load-constant --constant=CLD_IP --example=1.2.3.4 --default='$(wget -qO- ip.cldcloud.com)'

if ! grep -q "^NETWORK_POLICY=" /var/cld/creds/creds
then
    echo "Select network security policy" 
    select ANSWER in general private paranoid
    do
        if [ "${ANSWER}" == "general" ]; then
            echo NETWORK_POLICY=general >> /var/cld/creds/creds
            break
        elif [ "${ANSWER}" == "private" ]; then
            echo NETWORK_POLICY=private >> /var/cld/creds/creds
            break
        elif [ "${ANSWER}" == "paranoid" ]; then
            echo NETWORK_POLICY=paranoid >> /var/cld/creds/creds
            break
        else
            echo NETWORK_POLICY=general >> /var/cld/creds/creds
            break
        fi
    done
fi

if ! grep -q "^MIKROTIK=" /var/cld/creds/creds
then
	echo "Are you using MIKROTIK ?" 
	select ANSWER in yes no
	do
		if [ "${ANSWER}" == "yes" ]
			then
				init-load-constants MIKROTIK_USER\|admin MIKROTIK_PASSWORD\|Y0uRM1kr071Kp455W0rD MIKROTIK_HOST\|1.2.3.4 || echo skipped
				echo MIKROTIK=1 >> /var/cld/creds/creds
				break
		elif [ "${ANSWER}" == "no" ]
            then
				echo MIKROTIK=0 >> /var/cld/creds/creds
				break
		fi
	done
fi