#!/bin/bash
source /var/cld/bin/include/cldfuncs
init-load-constants ACCESS_BOT_TOKEN\|1234567890:AAEzBFqFii-uirfyG3PnygA0DAvJvRH7UzB ACCESS_API_DOMAIN\|cldapi.yourdomain.com

echo "Are you using MIKROTIK ?" 
select ANSWER in yes no
do
[ "${ANSWER}" == "yes" ] && init-load-constants MIKROTIK_USER\|admin MIKROTIK_PASSWORD\|Y0uRM1kr071Kp455W0rD MIKROTIK_HOST\|1.2.3.4
[ "${ANSWER}" == "no" ] && break
done